on:
  push:

name: Push Workflow
jobs:
  build:
    name: Test library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run tests
        run: |
          npm ci
          npm run test